//{{NO_DEPENDENCIES}}
// Microsoft Visual C++에서 생성한 포함 파일입니다.
// Tool.rc에서 사용되고 있습니다.
//
#define IDD_ABOUTBOX                    100
#define IDP_OLE_INIT_FAILED             100
#define IDR_MAINFRAME                   128
#define IDR_ToolTYPE                    130
#define IDD_GAMEVIEW                    310
#define IDD_HIERACHYVIEW                311
#define IDD_COMPONENTVIEW               312
#define IDD_BUTTONVIEW                  313
#define IDD_DEBUGVIEW                   314
#define IDD_TRANSFORMDLG                315
#define IDD_LISTDLG                     317
#define IDD_ANIMATORDLG                 318
#define IDD_ADDANIMDLG                  319
#define IDD_COMLISTDLG                  320
#define IDD_SCRIPTDLG                   321
#define IDD_HIERACHYDLG                 322
#define IDD_RESDLG                      323
#define IDD_OBJECTINFODLG               325
#define IDD_MATERIALDATADLG             326
#define IDD_LIGHTDLG                    327
#define IDD_ADDMATERIAL                 328
#define IDD_CAMERADLG                   329
#define IDD_TEXTDLG                     330
#define IDD_TERRAINDLG                  331
#define IDD_COLLIDERDLG                 332
#define IDD_CMESHRENDERDLGEX            333
#define IDR_MENU1                       334
#define IDR_RClick_MENU                 334
#define IDD_INTPARAMDLG                 336
#define IDD_FLOATPARAMDLG               337
#define IDD_VEC4PARAMDLG                338
#define IDD_TEXPARAM                    339
#define IDD_MESHRENDERDLG               340
#define IDD_MATERIALDLG                 341
#define IDD_LAYERSETTINGDLG             342
#define IDD_ANIMATOR_3DDLG              343
#define IDD_ADDANIMATION_3DDLG          344
#define IDD_ADDGAMEOBJECTDLG            345
#define IDD_TRAILDLG                    346
#define IDB_BITMAP1                     348
#define IDB_BITMAP2                     349
#define IDB_BITMAP3                     350
#define IDB_BITMAP4                     351
#define IDB_BITMAP5                     352
#define IDC_BUTTON1                     1000
#define IDC_TAG                         1000
#define IDC_BUTTON2                     1001
#define IDC_POS_X                       1001
#define IDC_LAYER                       1001
#define IDC_BUTTON3                     1002
#define IDC_POS_Y                       1002
#define IDC_POS_Z                       1003
#define IDC_MTRL                        1003
#define IDC_BUTTON7                     1003
#define IDC_ROT_X                       1004
#define IDC_COMBO1                      1004
#define IDC_BUTTON6                     1004
#define IDC_ROT_Y                       1005
#define IDC_MTRL2                       1005
#define IDC_BUTTON8                     1005
#define IDC_COMBO3                      1005
#define IDC_ROT_Z                       1006
#define IDC_BUTTON5                     1006
#define IDC_BUTTON9                     1006
#define IDC_SCA_X                       1007
#define IDC_LIST1                       1007
#define IDC_BUTTON10                    1007
#define IDC_SCA_Y                       1008
#define IDC_CHECK1                      1008
#define IDC_SCA_Z                       1009
#define IDC_EDIT9                       1009
#define IDC_EDIT1                       1009
#define IDC_EDIT2                       1010
#define IDC_CHECK2                      1010
#define IDC_EDIT3                       1011
#define IDC_DIR_X                       1011
#define IDC_CHECK3                      1011
#define IDC_EDIT4                       1012
#define IDC_LIST2                       1012
#define IDC_DIR_Y                       1012
#define IDC_CHECK4                      1012
#define IDC_EDIT5                       1013
#define IDC_TREE1                       1013
#define IDC_DIR_Z                       1013
#define IDC_EDIT10                      1013
#define IDC_CHECK5                      1013
#define IDC_EDIT6                       1014
#define IDC_TREE2                       1014
#define IDC_EDIT11                      1014
#define LAYER                           1016
#define IDC_CHECK6                      1016
#define IDC_EDIT7                       1017
#define IDC_BUTTON4                     1017
#define IDC_EDIT8                       1018
#define IDC_EDIT12                      1019
#define IDC_DIFF_R                      1020
#define IDC_EDIT13                      1020
#define IDC_DIFF_G                      1021
#define IDC_DIFF_B                      1022
#define IDC_SPEC_R                      1023
#define IDC_SPEC_G                      1024
#define IDC_SPEC_B                      1025
#define IDC_AMBI_R                      1026
#define IDC_AMBI_G                      1027
#define IDC_AMBI_B                      1028
#define IDC_ANGLE_OUT                   1029
#define IDC_ANGLE_IN                    1030
#define IDC_COMBO2                      1032
#define IDC_SLIDER1                     1035
#define IDC_RANGE                       1036
#define IDC_X                           1037
#define IDC_Y                           1038
#define IDC_Z                           1039
#define IDC_PIC2                        1039
#define IDC_W                           1040
#define IDC_LIST3                       1040
#define IDC_TOP_X                       1041
#define IDC_TOP_Y                       1042
#define IDC_TOP_Z                       1043
#define IDC_BOTTOM_X                    1044
#define IDC_BOTTOM_Y                    1045
#define IDC_BOTTOM_Z                    1046
#define ID_GAMEOBJECT_ADDGAMEOBJECT     32771
#define ID_SCENE_SAVE                   32772
#define ID_SCENE_LOAD                   32773
#define ID_GAMETOOL_TILETOOL            32774
#define ID_ADDRES_TEXTURE               32775
#define ID_ADDRES_MATERIAL              32776
#define ID_GAMEOBJECT_CREATETERRAIN     32777
#define ID_GAMEOBJECT_UI                32778
#define ID_UI_TEXT                      32779
#define ID_HIERARACY_DELETE             32780
#define ID_HIERARACY_ADDPREFAB          32781
#define ID_UI_BUTTON                    32782
#define ID_SCENE_LAYERSETTING           32783
#define ID_GAMEOBJECT_SAVEGAMEOBJECT    32784
#define ID_EFFECT_CREATEBASEEFFECT      32785
#define ID_HIERARACY_SAVEGAMEOBJ        32786
#define ID_PREFAB_INSTANTIATE           32787
#define ID_PREFAB_DELETE                32788
#define ID_GAMEOBJECT_PREFABINSTATIATE  32789
#define ID_ADDGAMEOBJECT_PREFAB         32790
#define ID_ADDGAMEOBJECT_BASIC          32791
#define ID_ADDGAMEOBJECT_WAYNODE        32792
#define ID_ADDGAMEOBJECT_SPAWN          32793

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        370
#define _APS_NEXT_COMMAND_VALUE         32794
#define _APS_NEXT_CONTROL_VALUE         1047
#define _APS_NEXT_SYMED_VALUE           347
#endif
#endif
